### ISSUE TITLE
Disabling specific swipe

### ISSUE THREAD

**Issue by vladimirhorvat** [lhandel/react-native-card-stack-swiper#12]
Using disable swiped (top, right, bottom or left) atributes only cancels calling onSwiped functions of that direction, but its still possible to swipe in that directions and card is removed from stack, next one is shown. Is there a way to fix this?

    <CardStack
          style={styles.content}
          renderNoMoreCards={() => <Text style={{fontWeight:'700', fontSize:18, color:'gray'}}>No more cards :(</Text>}
          ref={swiper => {
            this.swiper = swiper
          }}
         disableLeftSwipe = {true}
        >
          <Card style={[styles.card, styles.card1]} onSwipedLeft={() => alert('onSwipedLeft')}><Text style={styles.label}>A</Text></Card>
          <Card style={[styles.card, styles.card2]} onSwipedLeft={() => alert('onSwipedLeft')}><Text style={styles.label}>B</Text></Card>
          <Card style={[styles.card, styles.card1]} onSwipedLeft={() => alert('onSwipedLeft')}><Text style={styles.label}>C</Text></Card>
          <Card style={[styles.card, styles.card2]} onSwipedLeft={() => alert('onSwipedLeft')}><Text style={styles.label}>D</Text></Card>
          <Card style={[styles.card, styles.card1]} onSwipedLeft={() => alert('onSwipedLeft')}><Text style={styles.label}>E</Text></Card>
    </CardStack>

**Comment by lhandel** [comment]
The last update will fix this problem
