### ISSUE TITLE
Handling card onPress

### ISSUE THREAD

**Issue by lorencs** [lhandel/react-native-card-stack-swiper#17]
I'm trying to implement an onPress handler for each card by adding a Touchable wrapper inside the Card element. It seems to work for the 1st card, but for the 2nd and 3rd cards, the onPress event of the 3rd card is called. Similarly, for the 4th and 5th card, the onPress event of the 4th card is called. 

Seems like the cards are being rendered in pairs, and their order in the DOM is always the same regardless of one card being swiped away.

Is there any way to implement onPress properly?

**Comment by novakben** [comment]
Nothing out of the box. I modified the package abit to enable it, can be helpful for you- just don't have time to do PR. 

I added:
1. A new state prop: `slideGesture: false`
2. this logic in `componentWillMount`'s - `onPanResponderMove` method:
```
//Catch tap events
        const onTapCardDeadZone = 5;
        if (
            gestureState.dx < -onTapCardDeadZone ||
            gestureState.dx > onTapCardDeadZone ||
            gestureState.dy < -onTapCardDeadZone ||
            gestureState.dy > onTapCardDeadZone
        ) {
            this.setState({
                slideGesture: true
            })
        }
```

3. This in the `onPanResponderRelease` method:
```
if (!this.state.slideGesture && swipeDuration < 150) {
          this.props.onTap(this.state.sindex);
        }
        this.setState({ slideGesture: false });
```

Then I just pass an `onTap` prop to the `<CardStack />` component that uses the index to tell which card was pressed.

Break down in general:
When user starts a tap I starts measuring swipe distance, if it's bigger than my Deadzone (which I have set as 5), we know it's a swipe and not a tap and I pass to state a false flag on the slideGesture prop.

Then when user releases the tap, I check if it's a swipe or not and also hook on a time condition to make it more accurate. If it's a tap, the prop onTap function is called with the tapped card index.

Hope it helps!

**Comment by lorencs** [comment]
Thanks for the fast reply! It works almost perfectly. A couple adjustments I had to make:

- I had to subtract 2 from sindex as it seems to be the index of the next card to be rendered
- When setting slideGesture, I had to directly manipulate the state instead of using setState, otherwise the next card's zoom popped back to 0.95 after being swiped to. This is because the drag and dragDistance state properties are also directly manipulated in the onPanResponderMove function, and are overwritten if using setState for slideGesture 

Other than that, it works great. Again, thanks.

**Comment by novakben** [comment]
Right! forgot about the sindex issue! I think I addressed that as well somewhere in the code. 👍 

Weird, I don't have any issue with the setState, maybe because I added the code in the beginning of the method and I might have an issue waiting for me in the future.

If you have time I'm sure @lhandel would love the help integrating this.

**Comment by lhandel** [comment]
Is not it easier to just put a Touchable-component inside the card?

**Comment by lhandel** [comment]
It will know work to put Touchable-component inside a card for both android and iOS so I will close this one
