### ISSUE TITLE
How to disable gesture?

### ISSUE THREAD

**Issue by athaylean** [lhandel/react-native-card-stack-swiper#20]
Hi, I want to disable gesture, but leave animation only for buttons swipe. How can I do that?

**Comment by SmiljanicN** [comment]
Have you tried?
verticalSwipe={false}
horizontalSwipe={false}

**Comment by athaylean** [comment]
Yes, but the animation doesn't work. A while ago I copied code to editor and commented componentWillMount, in render function I deleted {...this._panResponder.panHandlers} and then animation was not there by itself, only on button click.
