### ISSUE TITLE
Making an async call in onSwiped

### ISSUE THREAD

**Issue by epord** [lhandel/react-native-card-stack-swiper#22]
I have an async function I want to call from onSwiped but instead of being asynchronous it is blocking and the swipe animation is not finishing until the async function is done:

``` javascript
async onSwiped(indexCard){
    /* some asynchronous operations */
}

<CardStack onSwiped={(indexCard) => {
                this.onSwiped(indexCard)
              }}
```

NOTE: Inside the async function I am setting some states

**Comment by lhandel** [comment]
This worked for me:
`
async onSwiped(indexCard){
    /* some asynchronous operations */
}

<CardStack  onSwiped={this. onSwiped.bind(this)}

`

**Comment by epord** [comment]
It works but the call is not asynchronous as I would expect, the animation is blocked until onSwiped() is finished
