### ISSUE TITLE
onSwipedLeft/onSwipedRight callbacks receive no args

### ISSUE THREAD

**Issue by darth-cheney** [lhandel/react-native-card-stack-swiper#36]
The docs indicate that the arg passed to the callbacks for `onSwipedLeft` and `onSwipedRight` (for `CardStack`) should receive the index in the stack of the card that was just swiped. From what I can tell this doesn't happen and there are no arguments passed at all.
  
Note that the example in this repo doesn't check for such an argument.

**Comment by lhandel** [comment]
It receives args when it used on the cardstack not the on the individual card.
