### ISSUE TITLE
Update Cards Dynamically

### ISSUE THREAD

**Issue by shandilya1998** [lhandel/react-native-card-stack-swiper#52]
I want to update cards dynamically based on the response from an API that i've made to update the contents of the card. I've created a function that onSwiped will call the API and a request is sent to the API to fetch the data for the new card. This is what the function looks like.
 ```
 fetchNextCardDetails = async () => {
    const response = await fetch("127.0.0.1:5000/get-next-card-details")
    const json = await response.json();
    this.setState({ dataNextCard : json });
}
```
I understand that i need to update a key in the card component to be able to render a new card with the new data. Now since i am getting the data from an API, how should i update the key? Can the key be any random number or does it have to be in a sequence. Each card contains information about a new place, which is obtained from google's places API, which is then sent to the react-native app. Can i use the place_id that i get from Google as a key instead of numbers? 
Fairly new with react-native needed help with my first app.

**Comment by lhandel** [comment]
You can just append the new card att the end of your list with cards
<CardStack onSwiped={this.addCard}>`
{cards.map((card, index) => (
            <Card key={card} style={[styles.card]}>
              <Text style={styles.label}>{card}</Text>
            </Card>
))}
</CardStack>`

`addCard = () => {
    const { cards } = this.state;
    cards.push('New card')
    this.setState({ cards })
  }`
