### ISSUE TITLE
How to flip the card

### ISSUE THREAD

**Issue by sheetalsuryan** [lhandel/react-native-card-stack-swiper#6]
is it possible to add flip feature this library, trying to add flipview in card but its flipping, could please help me to solve the same

**Comment by lhandel** [comment]
I don't think a flip feature fits in this module but you can combine [react-native-card-flip](https://github.com/lhandel/react-native-card-flip) with this module. Like shown below
`
<CardStack style={styles.content} ref={swiper => { this.swiper = swiper }}>
          <CardFlip style={[styles.cardContainer]} ref={(card) => this.card = card} >
            <TouchableOpacity activeOpacity={1} style={[styles.card, styles.card1]} onPress={() => this.card.flip()} ><Text style={styles.label}>AB</Text></TouchableOpacity>
            <TouchableOpacity activeOpacity={1} style={[styles.card, styles.card2]} onPress={() => this.card.flip()} ><Text style={styles.label}>CD</Text></TouchableOpacity>
          </CardFlip>
          <CardFlip style={[styles.cardContainer]} ref={(card) => this.card2 = card} >
            <TouchableOpacity activeOpacity={1} style={[styles.card, styles.card1]} onPress={() => this.card2.flip()} ><Text style={styles.label}>AB</Text></TouchableOpacity>
            <TouchableOpacity activeOpacity={1} style={[styles.card, styles.card2]} onPress={() => this.card2.flip()} ><Text style={styles.label}>CD</Text></TouchableOpacity>
          </CardFlip>
</CardStack>
`

**Comment by betiol** [comment]
In this case, how to get the `onSwipedLeft` event like the Card? I've tried to use with the `Card` component and not work :/
