### ISSUE TITLE
No cardIndex props?

### ISSUE THREAD

**Issue by georgeMorales** [lhandel/react-native-card-stack-swiper#61]
Hello, I used for a while react native deck swiper and with this library I had a cardIndex props and could save an index to start from there, in this library there is no similar props?
I also used a renderCard function, is the correct way to render all the items in the array with a map () and wrap the component in <Card>?
And ... is it possible to add overlayLabels LIKE and NOPE so that the user knows which swipe address is correct?
Thank you for this library, it works very well and the animation is very smooth :)

**Comment by lhandel** [comment]
Hi! I added initialIndex as a props to the CardStack (v.1.2.4). It works similar as initialScrollIndex on the Flatlist component.

**Comment by georgeMorales** [comment]
Thank you!
