### ISSUE TITLE
index is undefined.

### ISSUE THREAD

**Issue by harjeetxeno** [lhandel/react-native-card-stack-swiper#7]
In the function onSwipedRight={(index) =>     alert("index  is " + index)} the the index value is coming as undefined. 

I tried it on both card and cardstack. for card it is always undefined while in card stack the function is called twice once with undefined and second time with the correct index.

Can you please tell me whats going wrong ??

**Comment by lhandel** [comment]
The last update will fix this problem. It will return the swiped cards index on the cardstack
