### ISSUE TITLE
Single Card Rendering Not possible

### ISSUE THREAD

**Issue by tcyubahi** [lhandel/react-native-card-stack-swiper#8]
For some reason whenever there is only one Card Component inside CardStack, it is not rendered but rather "renderNoMoreCards" function is called.

**Comment by lhandel** [comment]
The last update will fix this problem

**Comment by jamesrowe08** [comment]
I believe this is fixed if it's the initial render but if you update the state that the underlying cards live in and that update only updates the list size to 1 then we still see this issue
