### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mitesh-db** [lhandel/react-native-card-stack-swiper#86]
Hii @lhandel ,

Is there any way I can handle pagination? when reaching some at point I need to add more data in array of card stack.

Or is there any way I can handle it with load more data in stack without refreshing whole content?

**Comment by Miancy** [comment]
Hey @mitjnextt ,
I am also facing this issue.
need Help..

**Comment by mitesh-db** [comment]
Did not get any success, Had to implement some custom logic

**Comment by Miancy** [comment]
> Did not get any success, Had to implement some custom logic

ohh nice, can you please share?

**Comment by mitesh-db** [comment]
Yes actually what I did was...
I rendered 5 items in Array at first, and then whenever users swipes Left or Right, using `onSwipedLeft` & `onSwipedRight` I pushed new card at the end of the array!
