### ISSUE TITLE
Array of cards

### ISSUE THREAD

**Issue by EzeInverni** [lhandel/react-native-card-stack-swiper#9]
Is it possible to load the cards from an array/list (one card generated for each element of the array) and later save them in another one (for example, disliked cards and liked cards)? Any tip on how to achieve it?

**Comment by lhandel** [comment]
You can use map

```javascript
 <CardStack style={styles.content} ref={swiper => { this.swiper = swiper }}>
{cards.map((item) => {
  return (
    <Card style={[styles.card, styles.card1]}><Text style={styles.label}>{item.title}</Text></Card>
  )
})}
</CardStack>
```

**Comment by EzeInverni** [comment]
Thank you!
